{% set name = "pyhepmc" %}
{% set version = "2.13.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pyhepmc-{{ version }}.tar.gz
  sha256: 5570b451eff4d11962b4f6155f5157eda5427c9db0f8193c644043ce3fc6af73

build:
  skip: true  # [py<38 or osx]
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
    - make
  host:
    - python
    - setuptools >=46.4
    - setuptools-scm >=6.2
    - cmake >=3.13
    - wheel
    - pip
  run:
    - python
    - numpy

test:
  imports:
    - pyhepmc
  commands:
    - pip check
  requires:
    - pip

about:
  summary: Pythonic interface to the HepMC3 C++ library licensed under LGPL-v3.
  home: https://scikit-hep.org/pyhepmc/
  license: BSD-3-Clause AND LGPL-3.0-only
  license_file:
    - LICENSE
    - extern/HepMC3/COPYING

extra:
  recipe-maintainers:
    - cvazquezs
