{% set name = "pyhepmc" %}
{% set version = "2.16.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pyhepmc-{{ version }}.tar.gz
  sha256: 7586baa7b1bcbd56636766e2bebf7457da9ec2f4f19bd683950915939b435d60

build:
  skip: true  # [py<39]
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  build:
    - python  # [build_platform != target_platform]
    - cross-python_{{ target_platform }}  # [build_platform != target_platform]
    - cmake >=3.13  # [build_platform != target_platform]
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
    - make
  host:
    - python
    - setuptools >=46.4
    - setuptools-scm >=6.2
    - cmake >=3.13
    - wheel
    - pip
  run:
    - python
    - numpy >=1.21
    - packaging

test:
  imports:
    - pyhepmc
  commands:
    - pip check
  requires:
    - pip

about:
  summary: Pythonic interface to the HepMC3 C++ library licensed under LGPL-v3.
  home: https://github.com/scikit-hep/pyhepmc
  license: BSD-3-Clause AND LGPL-3.0-only
  license_file:
    - LICENSE
    - extern/HepMC3/COPYING
  dev_url: https://github.com/scikit-hep/pyhepmc
  doc_url: https://scikit-hep.org/pyhepmc/

extra:
  recipe-maintainers:
    - conda-forge/scikit-hep
    - cvazquezs
